server:
  port: 8091

# actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
        # include: refresh

system:
  enabled: true

system-config:
  enabled: true
  max-attempts: 10
  options: optionA, optionB

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/hospitaldb
    username: postgres
    password: sysdba